curl -v -X POST http://localhost:8091/riak/quote/hoare -H 'Content-type: text/plain' -d 'There are two ways of constructing a software design: One way is to make it so simple that there are obviously no deficiencies and the other way is to make it so complicated that there are no obvious deficiencies.'
curl -v -X POST http://localhost:8091/riak/quote/dijkstra -H 'Content-type: text/plain' -d 'The computing scientists main challenge is not to get confused by the complexities of his own making.'
curl -v -X POST http://localhost:8091/riak/quote/bell -H 'Content-type: text/plain' -d 'The cheapest, fastest, and most reliable components are those that arent there.'
curl -v -X POST http://localhost:8091/riak/quote/thompson -H 'Content-type: text/plain' -d 'One of my most productive days was throwing away 1000 lines of code.'
curl -v -X POST http://localhost:8091/riak/quote/sickel -H 'Content-type: text/plain' -d 'Deleted code is debugged code.'
curl -v -X POST http://localhost:8091/riak/quote/kernighan -H 'Content-type: text/plain' -d 'Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it.'
curl -v -X POST http://localhost:8091/riak/quote/brianw -H 'Content-type: text/plain' -d 'The most effective debugging tool is still careful thought, coupled with judiciously placed print statements.'
curl -v -X POST http://localhost:8091/riak/quote/brian -H 'Content-type: text/plain' -d 'Controlling complexity is the essence of computer programming.'
curl -v -X POST http://localhost:8091/riak/quote/gelernter -H 'Content-type: text/plain' -d 'Beauty is more important in computing than anywhere else in technology because software is so complicated. Beauty is the ultimate defence against complexity.'
curl -v -X POST http://localhost:8091/riak/quote/gwyn -H 'Content-type: text/plain' -d 'UNIX was not designed to stop its users from doing stupid things, as that would also stop them from doing clever things.'
curl -v -X POST http://localhost:8091/riak/quote/carmack -H 'Content-type: text/plain' -d 'If youre willing to restrict the flexibility of your approach, you can almost always do something better.'
curl -v -X POST http://localhost:8091/riak/quote/viro -H 'Content-type: text/plain' -d 'And folks, lets be honest. Sturgeon was an optimist. Way more than 90% of code is crap.'
curl -v -X POST http://localhost:8091/riak/quote/gosper -H 'Content-type: text/plain' -d 'A data structure is just a stupid programming language.'
curl -v -X POST http://localhost:8091/riak/quote/wadler -H 'Content-type: text/plain' -d 'The essence of XML is this: the problem it solves is not hard, and it does not solve the problem well.'
